Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "public_network", ip: "192.168.1.69", guest:80, host:8080, auto_correct: true
  config.vm.synced_folder ".", "/var/www/html"  
config.vm.provider "virtualbox" do |vb|
  vb.memory = "1024" 
end

config.vm.provision "file", source: "../webseite/index.php", destination: "/var/www/html/index.php"
config.vm.provision "file", source: "../webseite/python/get_price.py", destination: "/var/www/html/python/get_price.py"
config.vm.provision "file", source: "../webseite/main.css", destination: "/var/www/html/main.css"

config.vm.provision "shell", inline: <<-SHELL
sudo apt-get update
sudo apt-get -y upgrade
sudo add-apt-repository ppa:deadsnakes/ppa  
sudo apt-get update  
sudo apt-get -y install python3.6
wget https://bootstrap.pypa.io/get-pip.py
sudo python3.6 get-pip.py
sudo apt-get -y install apache2
sudo apt -y install apache2 php libapache2-mod-php
sudo python3.6 -m pip install yahoo_fin 
sudo mkdir /var/www/html/python/tmp/
SHELL
end

